default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: a25632563

development:
  <<: *default
  database: monitoring_system_development

test:
  <<: *default
  database: monitoring_system_test

production:
  <<: *default
  database: monitoring_system_production
  username: monitoring_system
  password: <%= ENV['MONITORING_SYSTEM_DATABASE_PASSWORD'] %>
